# Generated by Django 3.0.6 on 2020-05-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_auto_20200524_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='connection',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
    ]
