# Generated by Django 3.0.6 on 2020-05-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_auto_20200524_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Counsumer 1', max_length=50)),
                ('Queue_Name', models.CharField(blank=True, default='Queue 1', max_length=100, null=True)),
                ('Pre_fetch', models.SmallIntegerField(default=2)),
                ('Time_to_Consume', models.SmallIntegerField(default=1)),
                ('Consumer_Tag', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Queue 1', max_length=50)),
                ('QueueName', models.SlugField(blank=True, null=True, unique=True)),
                ('Durable', models.BooleanField(default=True)),
                ('exchange', models.CharField(blank=True, max_length=100, null=True)),
                ('Routing_Key', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Consumer',
        ),
    ]
