# Generated by Django 3.0.6 on 2020-05-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20200519_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='port',
            field=models.SmallIntegerField(default=1884),
        ),
    ]
