# Generated by Django 3.0.6 on 2020-05-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_consumer_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='name',
            field=models.CharField(default='Counsumer 1', max_length=50),
        ),
    ]
