# Generated by Django 3.0.6 on 2020-05-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_auto_20200524_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='connection',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
