# Generated by Django 3.0.6 on 2020-05-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_auto_20200526_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createconsumer',
            old_name='Consumer_Tag',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='createqueue',
            name='QueueName',
        ),
        migrations.AddField(
            model_name='createqueue',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
